export function buildSetupGuide(ctx) {
  const date = new Date().toISOString().split('T')[0];
  const frameworkNames = ctx.frameworks.length > 0
    ? ctx.frameworks.join(', ')
    : 'None';

  return `# Claude Code Configuration Guide

This document describes how the \`.claude/\` directory is structured and how to
maintain it. Claude Code reads this file when you ask it to update or evolve
your configuration.

## Directory Structure

\`\`\`
.claude/
├── CLAUDE.md          Core project instructions (keep under ~150 lines)
├── settings.json      Permissions, MCP servers, hooks
├── skills/            Reusable workflows invoked with /skill-name
├── agents/            Specialized subagents for delegation
├── rules/             Path-scoped rules that load conditionally
└── SETUP-GUIDE.md     This file — meta-instructions for maintaining the config
\`\`\`

## Maintenance Rules

### CLAUDE.md Size Management
The main CLAUDE.md file should stay under ~150 lines. When it grows beyond that:

1. **Identify path-specific sections** — rules that only apply to certain files
   or directories (e.g., test conventions, API endpoint patterns)
2. **Move them to \`.claude/rules/[topic].md\`** with appropriate \`paths:\`
   frontmatter so they only load when relevant files are being edited
3. **Identify reference material** — content not needed every session
   (e.g., API docs, schema details)
4. **Move that to \`.claude/skills/[topic]/SKILL.md\`** so it can be invoked
   on demand

### When to Create a New Skill
- A repeatable multi-step workflow (deploy, fix-issue, review, etc.)
- Domain knowledge only needed sometimes (API reference, database schema)
- When CLAUDE.md is getting too long with how-to reference material

Skill file format:
\`\`\`markdown
---
name: skill-name
description: What the skill does
---
Instructions for Claude when this skill is invoked...
\`\`\`

### When to Create a New Agent
- A task benefits from isolated context (security audit, large search)
- You want to restrict tool access (read-only reviewer)
- The work would pollute the main conversation context

Agent file format:
\`\`\`markdown
---
name: agent-name
description: What the agent does
tools: Read, Glob, Grep
model: sonnet
---
System prompt for the agent...
\`\`\`

### When to Create a New Rule
- Instructions only apply to certain file types or directories
- You want conditional loading to keep the main CLAUDE.md context-efficient

Rule file format:
\`\`\`markdown
---
paths: ["src/api/**", "**/*.route.*"]
---
Rules that apply only when working in matched paths...
\`\`\`

### Settings.json Management
- **permissions.allow**: Add commonly-approved tool commands to reduce approval
  prompts during development. Review periodically to keep the list minimal.
- **mcpServers**: Add MCP servers as you adopt new external tools.
  Update tokens and connection strings as needed.
- **hooks**: Add hooks for deterministic automation (auto-format on save,
  lint before commit). Hooks run shell commands in response to Claude events.

## OS-Specific Notes (${ctx.os})
${getOsNotes(ctx.os)}

## IDE Notes (${ctx.ide.name})
${getIdeNotes(ctx.ide.id)}

---

*Configuration generated by create-claude-config v1.0.0*
*Generated: ${date}*
*Language: ${ctx.language.name}*
*Frameworks: ${frameworkNames}*
*Experience level: ${ctx.experience}*
`;
}

function getOsNotes(os) {
  switch (os) {
    case 'windows':
      return `- Claude Code uses bash syntax in its shell — forward slashes for paths
- Use Git Bash or WSL terminal for best compatibility
- File paths in CLAUDE.md should use forward slashes (e.g., src/utils/helper.js)`;

    case 'mac':
      return `- Claude Code works natively in the macOS terminal
- Homebrew is recommended for installing CLI tools (node, git, gh)`;

    case 'linux':
      return `- Claude Code works natively in Linux terminals
- Ensure Node.js 18+ is installed via your package manager or nvm`;

    default:
      return '';
  }
}

function getIdeNotes(ideId) {
  switch (ideId) {
    case 'vscode':
      return `- Claude Code integrates directly with VS Code via the Claude Code extension
- Use the built-in terminal panel for CLI access to Claude Code
- Claude can open and navigate files directly in your editor`;

    case 'jetbrains':
      return `- Claude Code integrates with JetBrains IDEs via the Claude Code plugin
- Use the built-in terminal for CLI access`;

    case 'terminal':
      return `- Run \`claude\` in your project root to start a session
- Use \`claude -p "prompt"\` for quick single-shot commands
- Use \`claude --help\` to see all CLI options`;

    case 'cursor':
      return `- Claude Code runs alongside Cursor via the integrated terminal
- They provide complementary AI capabilities`;

    default:
      return `- Run \`claude\` in your project root to start Claude Code`;
  }
}
